In [ ]:
#Fill missing salary using group-aware mean (per dept)
#Filter to only employees in 'ML' with experience above 2
#Print just the name and salary columns of that filtered result

In [8]:
import pandas as pd
df = pd.DataFrame({
    'name': ['Zoya', 'Arjun', 'Neha', 'Farhan'],
    'dept': ['ML', 'SDE', 'ML', 'SDE'],
    'salary': [88000, None, 92000, 71000],
    'experience': [3, 5, 2, 4]
})
print(df)

     name dept   salary  experience
0    Zoya   ML  88000.0           3
1   Arjun  SDE      NaN           5
2    Neha   ML  92000.0           2
3  Farhan  SDE  71000.0           4

In [5]:
df['salary'].fillna(df.groupby('dept')['salary'].transform('mean'))

0    83666.666667
1    83666.666667
2    83666.666667
3    83666.666667
Name: salary, dtype: float64

In [6]:
# Just .mean() — see what shape this gives you
print(df.groupby('dept')['salary'].mean())

dept
ML     83666.666667
SDE    83666.666667
Name: salary, dtype: float64

In [7]:
# Now .transform('mean') — see how this is different
print(df.groupby('dept')['salary'].transform('mean'))

0    83666.666667
1    83666.666667
2    83666.666667
3    83666.666667
Name: salary, dtype: float64

In [9]:
df = pd.DataFrame({
    'name': ['Zoya', 'Arjun', 'Neha', 'Farhan'],
    'dept': ['ML', 'SDE', 'ML', 'SDE'],
    'salary': [88000, None, 92000, 71000],
    'experience': [3, 5, 2, 4]
})

df['salary'].fillna(df.groupby('dept')['salary'].transform('mean'), inplace=True)
print(df)

     name dept   salary  experience
0    Zoya   ML  88000.0           3
1   Arjun  SDE  71000.0           5
2    Neha   ML  92000.0           2
3  Farhan  SDE  71000.0           4

C:\Users\sowmy\AppData\Local\Temp\ipykernel_9284\1930477359.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['salary'].fillna(df.groupby('dept')['salary'].transform('mean'), inplace=True)

In [20]:
#Filter to only employees in 'ML' with experience above 2
df[(df['dept']=='ML')&(df['experience']>2)]

   name dept   salary  experience
0  Zoya   ML  88000.0           3

In [21]:
employees = pd.DataFrame({
    'name': ['Zoya', 'Arjun', 'Neha', 'Farhan', 'Priya'],
    'dept': ['ML', 'SDE', 'ML', 'Data', 'Design']
})

dept_info = pd.DataFrame({
    'dept': ['ML', 'SDE', 'Data'],
    'head': ['Anita', 'Suresh', 'Kavya']
})

In [29]:
employees.merge(dept_info,on='dept',how='left')

     name    dept    head
0    Zoya      ML   Anita
1   Arjun     SDE  Suresh
2    Neha      ML   Anita
3  Farhan    Data   Kavya
4   Priya  Design     NaN

In [30]:
employees.merge(dept_info,on='dept',how='inner')

     name  dept    head
0    Zoya    ML   Anita
1   Arjun   SDE  Suresh
2    Neha    ML   Anita
3  Farhan  Data   Kavya

In [31]:
employees.merge(dept_info,on='dept',how='outer')

     name    dept    head
0  Farhan    Data   Kavya
1   Priya  Design     NaN
2    Zoya      ML   Anita
3    Neha      ML   Anita
4   Arjun     SDE  Suresh

In [32]:
jan = pd.DataFrame({
    'name': ['Zoya', 'Arjun'],
    'sales': [5000, 3000]
})

feb = pd.DataFrame({
    'name': ['Neha', 'Farhan'],
    'sales': [4500, 6000]
})

combined = pd.concat([jan, feb])
print(combined)

     name  sales
0    Zoya   5000
1   Arjun   3000
0    Neha   4500
1  Farhan   6000

In [35]:
combined = pd.concat([jan, feb], ignore_index=True)
print(combined)

     name  sales
0    Zoya   5000
1   Arjun   3000
2    Neha   4500
3  Farhan   6000